name: Pets
author: Driesboy
description: Simple Pets Plugin By BalAnce + Driesboy + Lifeboat
version: 2.0.0 
main: pets\main
api: [2.0.0] 
commands:
    pets:
        usage: /pets
        description: pets command
        aliases: pets
permissions:
    pets:
        default: true
        description: Allows all pets Features        
